{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1bf8f6a7-f0a4-443d-85e4-4287cc058cb8",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x20ddc995c50>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading from : //biod2100/DataFolder/W093/D2\n",
      "Loading from : //biod2100/DataFolder/W094/D1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2025-02-25 08:40:11,238] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\dash.py\", line 1373, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\_callback.py\", line 465, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\_callback.py\", line 40, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\dashboard.py\", line 521, in plotSingles\n",
      "    fig= self.Plot('Singles')\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\dashboard.py\", line 696, in Plot\n",
      "    fig= self.PlotSingle( )\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\dashboard.py\", line 737, in PlotSingle\n",
      "    figs.append(dcc.Graph(figure=fig))\n",
      "                                 ^^^\n",
      "UnboundLocalError: cannot access local variable 'fig' where it is not associated with a value\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 772, in handle_user_exception\n",
      "    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\_jupyter.py\", line 465, in _wrap_errors\n",
      "    ipytb()\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in __call__\n",
      "    self.handler()\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1278, in handler\n",
      "    ostream.write(self.text(etype, evalue, etb))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 446, in text\n",
      "    tb_list = self.structured_traceback(etype, value, tb,\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1339, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1186, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1076, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1173, in get_records\n",
      "    res = list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\stack_data\\core.py\", line 597, in stack_data\n",
      "    yield from collapse_repeated(\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\stack_data\\utils.py\", line 83, in collapse_repeated\n",
      "    yield from map(mapper, original_group)\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\stack_data\\core.py\", line 587, in mapper\n",
      "    return cls(f, options)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\stack_data\\core.py\", line 551, in __init__\n",
      "    self.executing = Source.executing(frame_or_tb)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 264, in executing\n",
      "    source = cls.for_frame(frame)\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 183, in for_frame\n",
      "    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 212, in for_filename\n",
      "    return cls._for_filename_and_lines(filename, tuple(lines))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 223, in _for_filename_and_lines\n",
      "    result = source_cache[(filename, lines)] = cls(filename, lines)\n",
      "                                               ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 163, in __init__\n",
      "    self.tree = ast.parse(self.text, filename=filename)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\ast.py\", line 50, in parse\n",
      "    return compile(source, filename, mode, flags,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "SystemError: AST constructor recursion depth mismatch (before=117, after=93)\n",
      "Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\dash.py\", line 1373, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\_callback.py\", line 465, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\_callback.py\", line 40, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\dashboard.py\", line 521, in plotSingles\n",
      "    fig= self.Plot('Singles')\n",
      "         ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\dashboard.py\", line 696, in Plot\n",
      "    fig= self.PlotSingle( )\n",
      "         ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\dashboard.py\", line 737, in PlotSingle\n",
      "    figs.append(dcc.Graph(figure=fig))\n",
      "                                 ^^^^^\n",
      "UnboundLocalError: cannot access local variable 'fig' where it is not associated with a value\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 772, in handle_user_exception\n",
      "    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\_jupyter.py\", line 465, in _wrap_errors\n",
      "    ipytb()\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1287, in __call__\n",
      "    self.handler()\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1278, in handler\n",
      "    ostream.write(self.text(etype, evalue, etb))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 446, in text\n",
      "    tb_list = self.structured_traceback(etype, value, tb,\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1339, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1186, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1076, in format_exception_as_a_whole\n",
      "    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1173, in get_records\n",
      "    res = list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\stack_data\\core.py\", line 597, in stack_data\n",
      "    yield from collapse_repeated(\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\stack_data\\utils.py\", line 83, in collapse_repeated\n",
      "    yield from map(mapper, original_group)\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\stack_data\\core.py\", line 587, in mapper\n",
      "    return cls(f, options)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\stack_data\\core.py\", line 551, in __init__\n",
      "    self.executing = Source.executing(frame_or_tb)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 264, in executing\n",
      "    source = cls.for_frame(frame)\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 183, in for_frame\n",
      "    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 212, in for_filename\n",
      "    return cls._for_filename_and_lines(filename, tuple(lines))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 223, in _for_filename_and_lines\n",
      "    result = source_cache[(filename, lines)] = cls(filename, lines)\n",
      "                                               ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\executing\\executing.py\", line 163, in __init__\n",
      "    self.tree = ast.parse(self.text, filename=filename)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\ast.py\", line 50, in parse\n",
      "    return compile(source, filename, mode, flags,\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "SystemError: AST constructor recursion depth mismatch (before=117, after=93)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\werkzeug\\serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\werkzeug\\serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 1498, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 1476, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\flask\\app.py\", line 823, in handle_exception\n",
      "    server_error = self.ensure_sync(handler)(server_error)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\_jupyter.py\", line 449, in _wrap_errors\n",
      "    skip = _get_skip(error) if dev_tools_prune_errors else 0\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\DempBot\\DataBot\\Lib\\site-packages\\dash\\_jupyter.py\", line 45, in _get_skip\n",
      "    while tb.tb_next is not None:\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'tb_next'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "---------------------------------------------------------------------------\n",
      "UnboundLocalError                         Traceback (most recent call last)\n",
      "File c:\\DempBot\\dashboard.py:521, in Dashboard.appPlot.<locals>.plotSingles(single_clicks=1)\n",
      "    513 @app.callback(\n",
      "    514     Output('graphs','children', allow_duplicate=True),\n",
      "    515     Output('bSingles','n_clicks'),\n",
      "   (...)\n",
      "    518     running=[(Output(\"graphSpacer\", \"children\"), 'Loading', ' - ')])\n",
      "    519 def plotSingles(single_clicks ):\n",
      "    520     if single_clicks>0:\n",
      "--> 521         fig= self.Plot('Singles')\n",
      "        self = <dashboard.Dashboard object at 0x0000020DDE85F190>\n",
      "    522         return fig,0\n",
      "    523     return [],0\n",
      "\n",
      "File c:\\DempBot\\dashboard.py:696, in Dashboard.Plot(\n",
      "    self=<dashboard.Dashboard object>,\n",
      "    graphType='Singles'\n",
      ")\n",
      "    693 fig=[]\n",
      "    695 if graphType =='Singles' : \n",
      "--> 696     fig= self.PlotSingle( )\n",
      "        fig = []\n",
      "        self = <dashboard.Dashboard object at 0x0000020DDE85F190>\n",
      "    697 elif graphType =='Ensemble':\n",
      "    698     fig = self.PlotEnsemble( )\n",
      "\n",
      "File c:\\DempBot\\dashboard.py:737, in Dashboard.PlotSingle(self=<dashboard.Dashboard object>)\n",
      "    735     elif self.dataType == 'RT':\n",
      "    736         fig = self._PlotRT(channel,self.selectedAnalytes)\n",
      "--> 737     figs.append(dcc.Graph(figure=fig))\n",
      "        figs = []\n",
      "        dcc.Graph = <class 'dash.dcc.Graph.Graph'>\n",
      "        dcc = <module 'dash.dcc' from 'c:\\\\DempBot\\\\DataBot\\\\Lib\\\\site-packages\\\\dash\\\\dcc\\\\__init__.py'>\n",
      "    739 return figs \n",
      "\n",
      "UnboundLocalError: cannot access local variable 'fig' where it is not associated with a value\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "UnboundLocalError                         Traceback (most recent call last)\n",
      "File c:\\DempBot\\dashboard.py:521, in Dashboard.appPlot.<locals>.plotSingles(single_clicks=2)\n",
      "    513 @app.callback(\n",
      "    514     Output('graphs','children', allow_duplicate=True),\n",
      "    515     Output('bSingles','n_clicks'),\n",
      "   (...)\n",
      "    518     running=[(Output(\"graphSpacer\", \"children\"), 'Loading', ' - ')])\n",
      "    519 def plotSingles(single_clicks ):\n",
      "    520     if single_clicks>0:\n",
      "--> 521         fig= self.Plot('Singles')\n",
      "        self = <dashboard.Dashboard object at 0x0000020DDE85F190>\n",
      "    522         return fig,0\n",
      "    523     return [],0\n",
      "\n",
      "File c:\\DempBot\\dashboard.py:696, in Dashboard.Plot(\n",
      "    self=<dashboard.Dashboard object>,\n",
      "    graphType='Singles'\n",
      ")\n",
      "    693 fig=[]\n",
      "    695 if graphType =='Singles' : \n",
      "--> 696     fig= self.PlotSingle( )\n",
      "        fig = []\n",
      "        self = <dashboard.Dashboard object at 0x0000020DDE85F190>\n",
      "    697 elif graphType =='Ensemble':\n",
      "    698     fig = self.PlotEnsemble( )\n",
      "\n",
      "File c:\\DempBot\\dashboard.py:737, in Dashboard.PlotSingle(self=<dashboard.Dashboard object>)\n",
      "    735     elif self.dataType == 'RT':\n",
      "    736         fig = self._PlotRT(channel,self.selectedAnalytes)\n",
      "--> 737     figs.append(dcc.Graph(figure=fig))\n",
      "        figs = []\n",
      "        dcc.Graph = <class 'dash.dcc.Graph.Graph'>\n",
      "        dcc = <module 'dash.dcc' from 'c:\\\\DempBot\\\\DataBot\\\\Lib\\\\site-packages\\\\dash\\\\dcc\\\\__init__.py'>\n",
      "    739 return figs \n",
      "\n",
      "UnboundLocalError: cannot access local variable 'fig' where it is not associated with a value\n",
      "\n",
      "Loading from : //biod2100/DataFolder/W093/D2\n",
      "Loading from : //biod2100/DataFolder/W094/D1\n",
      "Loading from : //biod2100/DataFolder/W093/D2\n",
      "Loading from : //biod2100/DataFolder/W095/A3\n"
     ]
    }
   ],
   "source": [
    "from dashboard import Dashboard\n",
    "from IPython.display import display, HTML\n",
    "\n",
    "dashboard = Dashboard( )        \n",
    "dashboard.CreateIVDash() "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cbfbf0ca-6beb-4047-b83a-f7c176a95d35",
   "metadata": {},
   "outputs": [],
   "source": [
    "#display(HTML(\"<style>.container { height:1800px !important; }</style>\"))\n",
    "#display(HTML(\"<style>.output_result { height:1800px !important; }</style>\"))\n",
    "#display(HTML(\"\"\"<style>\n",
    "#.jp-OutputArea-output { height:1800px  !important; }\n",
    "#.jp-Cell-outputArea { height:1800px  !important; }\n",
    "#.jp-OutputArea   { height:1800px  !important; }            \n",
    "#             </style>\"\"\"))\n",
    "#lm-Widget jp-OutputArea "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
